Added set of Review to AmazonUser models. Added InjectController and …
MaksymVakuliuk/spring-boot-project pull request #9
Opened 2020-07-21 11:54 UTC by MaksymVakuliuk

…SecurityCondig. Added datasource url to application properties.

2020-07-29 12:15 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/config/SecurityConfig.java
> +        http.formLogin();
```suggestion
        http.formLogin()
            .authorizeRequests()
            ....
```
Можна зробити це одним pipeline

2020-07-29 12:16 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/controllers/AmazonUserController.java
> +    public List<AmazonUserDto> getMostActiveUser(@PathVariable int numberOfAmazonUsers) {
PathVariable використовуємо тільки для ідентифікаторів. Кількість юзерів не є ідетифікатором. Використовуй RequestParam

2020-07-29 12:17 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/controllers/ProductController.java
> +    @GetMapping("/mostcommented/{numberOfProducts}")
аналогічно як і з користувачами

2020-07-29 12:17 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/controllers/ReviewController.java
> +    @GetMapping("/mostusedwords/{numberOfWords}")
аналогічно

2020-07-29 12:26 UTC, boroda4436 requested changes

2020-07-29 12:26 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/dto/review/ReviewMapper.java
> +                .setProductDto(new ProductMapper().convertToAmazonUserDto(review.getProduct()));
ProductMapper в тебе компонент. Не використовуй new в SPRING! Заюзай autowired
```suggestion
                .setProductDto(productMapper.convertToAmazonUserDto(review.getProduct()));
```

2020-07-29 12:26 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/service/GenericService.java
> +public interface GenericService<T,I> {
```suggestion
public interface GenericService<T,ID> {
```
Так буде більш читабельно

2020-07-29 12:26 UTC, boroda4436 commented on src/main/java/com/spring/boot/project/demo/service/impl/ReviewServiceImpl.java
> +    private void addDataToDatabase(Iterable<AmazonUser> amazonUsers,
Цей метод використовується тільки в одному місці. Тому немає сенсу виносити ці операції в окремий метод. По суті тут ти не досягаєш реюзабельності коду

2020-07-29 12:26 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/controllers/AmazonUserControllerTest.java
> +}
empty line?

2020-07-29 12:26 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/controllers/ProductControllerTest.java
> +}
empty line

2020-07-29 12:26 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/controllers/ReviewControllerTest.java
> +}
empty line

2020-07-29 12:26 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/repository/ReviewRepositoryTest.java
> +        assertEquals(5, reviewRepository.findAll().size());
А чому має бути саме 5 review? Звідки вони потрапили в БД?

2020-07-29 12:26 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/repository/AmazonUserRepositoryTest.java
> +    private AmazonUserRepository amazonUserRepository;
@MaksymVakuliuk Бачу, що додав окрему БД для тестів в application.properties. Вірно?

2020-07-29 12:28 UTC, MaksymVakuliuk commented on src/test/java/com/spring/boot/project/demo/repository/AmazonUserRepositoryTest.java
> +    private AmazonUserRepository amazonUserRepository;
Так

2020-07-29 12:47 UTC, MaksymVakuliuk commented on src/test/java/com/spring/boot/project/demo/controllers/AmazonUserControllerTest.java
> +}
Поправлю.

2020-07-29 12:48 UTC, MaksymVakuliuk commented on src/test/java/com/spring/boot/project/demo/repository/ReviewRepositoryTest.java
> +        assertEquals(5, reviewRepository.findAll().size());
Були добаленны в базу данных в InjectCantroller @PostConstruct. Тому чтоо в базе данных на момент теста нааходться пять коментфриев.

2020-07-29 12:50 UTC, MaksymVakuliuk commented on src/main/java/com/spring/boot/project/demo/service/GenericService.java
> +public interface GenericService<T,I> {
Да согласен, опирался на то что Generics обозначают одной большой букваой.

2020-07-29 12:51 UTC, MaksymVakuliuk commented on src/main/java/com/spring/boot/project/demo/config/SecurityConfig.java
> +        http.formLogin();
Ок, переделаю)

2020-07-29 12:51 UTC, MaksymVakuliuk commented on src/main/java/com/spring/boot/project/demo/controllers/AmazonUserController.java
> +    public List<AmazonUserDto> getMostActiveUser(@PathVariable int numberOfAmazonUsers) {
Ок, переделаю)

2020-07-29 14:38 UTC, boroda4436 commented on src/test/java/com/spring/boot/project/demo/repository/ReviewRepositoryTest.java
> +        assertEquals(5, reviewRepository.findAll().size());
> Это звоночек о том что здесь нужно юзать контанту?

Ні.

> Были добаленны в базу данных в InjectCantroller @PostConstruct. 

А оце звоночок. В твоїх тестах, дані для тестів повинні додаватися при самому тесті. А виходить, що ти залежиш від сторонньої реалізації. Тест не зовсім unit test. Це вже більше виглядає як integration test

2020-07-29 20:28 UTC, MaksymVakuliuk commented on src/main/java/com/spring/boot/project/demo/service/GenericService.java
> +public interface GenericService<T,I> {
Оставил так как есть из-за того что не проходит тест на code style.

2020-07-30 09:40 UTC, boroda4436 approved these changes

2020-07-30 09:58 UTC, merged